name: Offline forecast run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  offline_forecast:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run offline bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          poetry run python offline_main.py

      - name: Upload forecast artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: forecast-results-${{ github.run_id }}
          path: forecasts/fall/
          retention-days: 30

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Check for changes and commit
        id: changes
        run: |
          git add forecasts/fall/
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected, creating commit"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            git commit -m "Update offline forecast results - $(date -u +'%Y-%m-%d %H:%M:%S UTC')

            🤖 Generated with automated offline forecasting bot

            Co-Authored-By: Claude <noreply@anthropic.com>"
          fi

      - name: Push changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git push origin main
